# 配置文件
mysql:
  dns: root:rootroot@tcp(127.0.0.1:3306)/go_gin_chat_db?charset=utf8mb4&parseTime=True&loc=Local

# redis的链接信息
redis:
  addr: "localhost:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30